const MyImage = {
    defaultAvatar       : require('../../src/images/avatar.png'),
    splashScreen        : require("../../src/images/avatar.png"),
    icon                : require("../../src/images/icon.png"),
    icon512             : require("../../src/images/icon_512.png"),
    icon_bg            : require("../../src/images/icon_bg.png"),
    logo_white          : require("../../src/images/logo_white.png"),
    logo512             : require("../../src/images/logo.png"),
    logo1024            : require("../../src/images/logo_1024.png"),
    defaultItem         : require("../../src/images/no_image.png"),
    defaultBanner       : require("../../src/images/photo.png"),
    defaultBannerProduct: require("../../src/images/no_image.png"),
    defaultSource       : require("../../src/images/logo.png"),
    defaultDrawer       : require("../../src/images/logo.png"),
    electronics_pattern : require("../../src/images/electronics_pattern.png"),

    camera            : require("../../src/images/camera.png"),
    customer_service  : require("../../src/images/customer_service.png"),
    customer_service_2: require("../../src/images/customer_service_2.png"),
    shop              : require("../../src/images/shop.png"),
    monitor           : require("../../src/images/monitor.png"),
    phone             : require("../../src/images/phone.png"),
    call              : require("../../src/images/call.png"),
    notification      : require("../../src/images/notification.png"),
    bag               : require("../../src/images/bag.png"),
    rate              : require("../../src/images/rate.png"),
    power_off         : require("../../src/images/power_off.png"),
    browser           : require("../../src/images/browser.png"),
    key               : require("../../src/images/key.png"),
    info              : require("../../src/images/info.png"),

    onError: "../../src/images/logo.png",

    lottie_empty_lost      : require("../../src/images/lottie_empty_lost.json"),
    lottie_bus             : require("../../src/images/lottie_bus.json"),
    lottie_confirmation    : require("../../src/images/lottie_confirmation.json"),
    lottie_check_in_success: require("../../src/images/lottie_check_in_success.json"),
    lottie_searching_file  : require("../../src/images/lottie_searching_file.json"),
    lottie_developer       : require("../../src/images/lottie_developer.json"),
    lottie_box_open        : require("../../src/images/lottie_box_open.json"),
    lottie_map_marker      : require("../../src/images/lottie_map_marker.json"),
    lottie_location        : require("../../src/images/lottie_location.json"),
    lottie_love            : require("../../src/images/lottie_love.json"),
};

export default MyImage;
