import LocalizedStrings from 'react-native-localization';
import {Text} from "react-native";
import React from "react";

export default new LocalizedStrings(
    {
        en: {
            AppName: 'DirectD',

            AppVersion                : "App Version",
            Exit                      : "Exit",
            ExitConfirm               : "Are you sure you want to exit this app",
            Yes                       : "Yes",
            No                        : "No",
            OK                        : "OK",
            ViewMyOrders              : "View My Oders",
            CANCEL                    : "CANCEL",
            Confirm                   : "Confirm",
            Retry                     : "RETRY",
            PleaseWait                : "Please Wait",
            LogginOut                 : "Logging Out...",
            Attention                 : "Attention",
            Loading                   : "Loading",
            DeleteAlert               : "Are you sure to delete",
            UpdateAlert               : "New version is available at play store.\nWould you like to update now?",
            LoginRequired             : "You need to Login to access this service",
            LogoutConfirmation        : "Are you sure you want to logout",
            BiometryNAFingerprint     : "Please login first using email/password or Facebook/Google to enable Fingerprint login",
            BiometryVerificationFailed: "Unable to verify your biometry",
            LoginSuccessfully         : "Login Successfully",
            LogoutSuccessfully        : "Logout Successfully",
            UnknownError              : "Unknown Error",
            ResponseNotFound          : "Error response not found",
            OperationCanceledByUser   : "Operation canceled by user",
            SessionExpired            : "Your Session has Expired, Please Login Again",
            PasswordResetCodeSent     : "Password reset code has been sent",
            PasswordResetSuccessfull  : "Password reset successful\nPlease use the new password to login now",
            PleaseEnterEmailAddress   : "Please enter email address in forgot password page",
            PleaseLoginFirst          : "Please login first",
            ErrorNotFound             : "Error Not Found",
            Error                     : "Error",
            Ok                        : "Ok",
            Allow                     : "Allow",
            Later                     : "Later",
            AskMeLater                : "Ask Me Later",
            AvailableStock            : "Available Stock",
            InStock                   : "In Stock",
            OutOfStock                : "Out of Stock",
            Permission                : {
                title   : "Permission Request",
                location: "This app needs location permission to delivery orders to your address"
            },

            GetCurrentAddress  : "Get Current Address",
            ExitAppConfirmation: "Press back again to exit App.",

            WriteSomethingHere: "write something here",
            HelperTextDefault : "No Message",
            BankInformation   : "Bank Information",
            BankName          : "Bank Name",
            BankCode          : "Bank Code",
            AccountHolderName : "Account Holder's Name",
            AccountNumber     : "Account Number",
            Accept            : "Accept",


            LoginToManageProfile                 : "Login to manage profile",
            ForgotYourPassword                   : "Forgot your password?",
            LoginTitleDescription                : "Use your email address and password to login",
            RegistrationTitleDescription         : "Create a new account either using email/password or facebook/google",
            RegistrationCompletedTitleDescription: "Congratulations, your account has been successfully created.",
            ForgotPasswordDescription            : "Please enter your email address to reset your password.",
            ResetPasswordDescription             : "Please enter the code you have received via email and your new password.",
            ChangePasswordCurrent                : "To change your password, please enter your current password below",
            ChangePasswordNew                    : "Enter your new and confirm password below and press the button",
            EditProfileDesc                      : "To update your profile information enter them below and press the button",
            PasswordUpdated                      : "Password updated",
            ProfileUpdated                       : "Profile updated",
            YouMayLoginNow                       : "You may login now from login page.",
            PressToLogin                         : "Press the button to login now into the app",
            WeWillVerify                         : "We will verify your account and let you know within 48 hours. Thank you for your patient.",
            OrConnectUsing                       : "Or connect using",
            OrRegisterUsing                      : "Or register using",
            LoginusingTouchID                    : "Login using TouchID",
            LoginUsingFingerPrint                : "Login using Fingerprint",
            DontHaveAnAccount                    : "Don't have an account?",
            AlreadyHaveAnAccount                 : "Already have an account?",
            AlreadyHaveCode                      : "Already have code?",
            DidnotReceivedCode                   : "Didn't receive code?",
            CountryListNotFound                  : "Country not found",
            StateListNotFound                    : "State not found",
            CityListNotFound                     : "City not found",
            PleaseSelectCountryFirst             : "Please select country first",

            isRequired       : "is required",
            mustBeMinimum    : "must be minimum",
            mustBeMaximum    : "can't be more than",
            character        : "character",
            InvalidEmail     : "Email address is invalid",
            InvalidPhone     : "Phone number is invalid",
            PasswordMustMatch: "Passwords must match",

            // Scene's Titles
            DummyProfile     : "Platinum",
            DummyPoints      : "1,150 Points",
            DummyNotification: "14",
            Home             : "Home",
            Intro            : "Intro",
            Product          : "Product",
            Price            : "Price",
            ProductDetails   : "Product Details",
            ProductBuy       : "Product Buy",
            WishList         : "WishList",
            Next             : "Next",
            Back             : "Back",

            Restaurants           : "Restaurants",
            Description           : "Description",
            Specification         : "Specification",
            Warranty              : "Warranty",
            Video                 : "Video",
            Review                : "Review",
            Reviews               : "Reviews",
            'Review(s)'           : "Review(s)",
            Catering              : "Catering",
            Cart                  : "Cart",
            MyPoints              : "My Points",
            MyOrders              : "My Orders",
            OrderDetails          : "Order Details",
            MyWishList            : "My WishList",
            MyAddress             : "My Address",
            MyAddresses           : "My Addresses",
            NewAddress            : "New Address",
            EditAddress           : "Edit Address",
            AddAddress            : "Add Address",
            ManageAddress         : "Manage Address",
            Reservations          : "Reservations",
            Notification          : "Notification",
            Notifications         : "Notifications",
            NotificationsDetails  : "Notification Details",
            Favorites             : "Favorites",
            Settings              : "Settings",
            RateApp               : "Rate App",
            ReferAndEarn          : "Refer & Earn",
            ReferAndEarnDetails   : "When a new user register using your referral code, you and the user both get RM10",
            ShareRefereCodeDetails: "Download the app and register using this referral code to earn RM 10",
            Share                 : "Share",
            ShareUs               : "Share Us",
            AppShare              : "DirectD App Share",
            About                 : "About",
            AboutUs               : "About Us",
            ContactUs             : "Contact Us",
            RefundPolicy          : "Refund Policy",
            TermsAndCondition     : "Terms & Condition",
            BankAccounts          : "BankAccounts",

            Facebook : "Facebook",
            Google   : "Google",
            GoogleMap: "Google Map",

            // Home
            products: "products",

            // TopBar
            ShowFilter  : "Sub Categories",
            HideFilter  : "Hide",
            Sort        : "Sort",
            textFilter  : "Recent",
            SelectSource: "Select Source",
            SelectImage : "Select Image",

            // Category
            ThereIsNoMore                     : "There is no more product to show",
            PageRefreshed                     : "Page Refreshed",
            ProfilePhotoUploadedSuccessfully  : "Profile Photo Uploaded Successfully",
            PaymentReceiptUploadedSuccessfully: "Payment Receipt Uploaded Successfully",
            AddressAddedSuccessfully          : "Address Added Successfully",
            AddressUpdatedSuccessfully        : "Address Updated Successfully",
            AddressDeletedSuccessfully        : "Address Deleted Successfully",
            FileUploadFailed                  : "File Upload Failed",
            FailedToAddAddress                : "Failed To Add Address",
            FailedToUpdateAddress             : "Failed To Update Address",
            FailedToDeleteAddress             : "Failed To Delete Address",
            InvalidAddress                    : "Invalid address, Please select a proper address.\nYou can use google map to select a valid address",
            AddressDeleteAlert                : "Are you sure you want to delete this address?\nPlease note that deleted items can't be restored",
            OrderPlaceAlert                   : "Are you sure you want to place this order?",
            OrderCancelAlert                  : "Are you sure you want to cancel this order?\nPlease note that cancelled order will take time to refund your money",
            OrderReturnAlert                  : "Are you sure you want to return this order?\nPlease note that returned order will take time to refund your money",
            PaymentWebViewAlert               : "Are you sure you want to go back?\nPlease note that your order will not be completed successfully if you go back from this page",
            CartItemRemoveAlert               : "Are you sure you want to remove this item from cart?",
            StayOnThisPage                    : "Stay On This Page",
            GoBack                            : "Go Back",
            IAmSure                           : "I am sure",
            YourAppIsUptoDate                 : "Your app is up to date",

            // Product
            AddtoCart                     : "Add to Cart",
            AddtoWishlist                 : "Add to Wishlist",
            ProductVariations             : "Variations",
            NoVariation                   : "This product don't have any variation",
            AdditionalInformation         : "Description",
            NoProductDescription          : "No Product Description",
            ProductReviews                : "Reviews",
            NoReview                      : "This product don't have any reviews ...yet",
            ProductLimitWaring            : "You can't add more than 10 product",
            EmptyProductAttribute         : "This product don't have any attributes",
            ProductFeatures               : "Features",
            ErrorMessageRequest           : "Can't get data from server",
            NoConnection                  : "No internet connection",
            LocationPermissionDenied      : "Location Permission Denied",
            InternetConnectionNotAvailable: "Internet connection not available",
            RequestFailed                 : "HTTP Request Failed",
            ProductRelated                : "You May Also Like",
            FormInvalid                   : "Please Check Your Inputs",
            ReferralCodeNotFound          : "Referral Code Not Found",
            CouponCodeInvalid             : "Please enter coupon code",
            KeyChainGetSupportedFailed    : "Unable to Get Supported Biometric Types",
            KeyChainStoreFailed           : "Unable to Store Sensitive Data",
            KeyChainRetriveFailed         : "Unable to Retrive Sensitive Data",
            KeyChainResetFailed           : "Unable to Reset Sensitive Data",
            StorageStoreFailed            : "Unable to Store Storage Data",
            StorageRetriveFailed          : "Unable to Retrive Storage Data",
            StorageRemoveFailed           : "Unable to Remove Storage Data",
            StorageClearFailed            : "Unable to Clear Storage Data",
            AndroidPermissionDenied       : "Permission Denied",
            AndroidPermissionNotGranted   : "Permission Not Granted",
            FirebaseTokenFailed           : "Push Notification might not work, Permission Denied",
            ImagePickerCanceled           : "Image Picker Canceled",
            ImagePickerError              : "Error in Image Picker",
            AllItemsLoadedInTheList       : "All items loaded in the list",
            LoginFailed                   : "Login Failed, Please Try Again",
            RegistrationFailed            : "Registration Failed, Please Try Again",
            LogoutFailed                  : "Logout Failed",
            GeocoderFailed                : "Unable to Retrive Geocoder",
            GeocoderComponentMissing      : "Unable to Retrive Proper Address",
            ShareFailed                   : "Unable to share",
            LinkOpenFailed                : "Unable to open link",
            PleaseVerifyForAuth           : "Please verify for authentication",
            FileFetchingFailed            : "Unable to fetch file from remote server",
            FilePickerFailed              : "Unable to open file picker",
            UnableToOpen                  : "Unable to open",
            GPSFailed                     : "Unable to Retrive Current Location",
            GPSPermissionRequest          : "Permission Denied\nPlease Allow GPS Permission to Allow this App to work properly",
            DeviceInfoFailed              : "Device Info Fetching Failed",
            GoogleLoginUserCanceled       : "User canceled google login",
            GoogleLoginInProgress         : "Google login already in progress",
            GoogleLoginNoPlayService      : "Google service not available, please install",
            GoogleLoginFailed             : "Google login failed",
            FacebookUserCanceled          : "User canceled facebook login",
            FacebookLoginFailed           : "Failed to login using facebook",
            FacebookLogoutFailed          : "Failed to logout from facebook",
            NoHomeItemsFound              : "This place is deserted",
            NoRestaurantFound             : "Seems like there is no restaurants nearby",
            NoCategoryFound               : "Seems like no category found in our vault",
            NoNotificationFound           : "You have no notifications",
            NoOrderFound                  : "You have not placed any orders yet",
            NoSavedAddressFound           : "No saved address found",
            NoProductFound                : "Seems like no product found in our vault",
            NoProductDetailsFound         : "Seems like no product details found",
            NoOrderDetailsFound           : "We are unable to find order details",
            NoNotificationDetailsFound    : "No details about this notification found",
            NoItemInYourCart              : "No item in your cart\nLet's add something from from our shop page",
            NoDataFoundInSearch           : "No data found in search query\nPlease try again",
            TypeSomethingToSearch         : "Type something to start searching",
            WeAreSearching                : "We are searching...",
            ComingSoon                    : "Currently in works",
            FeaturedProducts              : "Featured Products",
            NewArrivals                   : "New Arrivals",
            ViewAll                       : "View all",

            // Cart
            NoDescriptionFound              : "No Description Found",
            NoInformationFound              : "No Information Found",
            NoVideoAvailable                : "No Video Available",
            NoReviewsYet                    : "No Reviews Yet",
            NoText                          : "No text",
            NoCartItem                      : "There is no product in cart",
            EmptyCheckout                   : "Sorry, you can't check out an empty cart",
            RemoveCartItemConfirm           : "Remove this product from cart?",
            MyCart                          : "Cart",
            Order                           : "Order",
            OrderTotal                      : "Order Total",
            PlacedOn                        : "Placed On",
            ShoppingCart                    : "Shopping Cart",
            ShoppingCartIsEmpty             : "Your Cart is Empty",
            DeliveryType                    : "Delivery Type",
            DeliveryTypeDesc                : "Select your preferred delivery type",
            FilterCategoryRequired          : "Please select 1 category to filter",
            OrderUnableToCancel             : "Sorry\nWe are unable to cancel your order as it's already ",
            OrderUnableToReturn             : "Sorry\nWe are unable to return your order as it's already ",
            OrderUnableToUploadReceipt      : "Sorry\nWe are unable to accept payment receipt as your order is already ",
            OrderCancelledSuccessfully      : "Order has been cancelled successfully",
            DeliveryMethod                  : "Delivery Method",
            TrackingInformation             : "Tracking Information",
            TrackingID                      : "Tracking ID",
            TrackingNumber                  : "Tracking Number",
            CurrentStatus                   : "Current Status",
            DeliveryCost                    : "Delivery Cost",
            DeliveryMethodUpdated           : "Delivery Method Updated",
            OrderPlacedSuccessfully         : "Order Placed Successfully",
            InstallmentAmountUpdated        : "Installment amount updated",
            InstallmentAmountUpdateFailed   : "Installment amount update failed",
            OrderPlacedFailed               : "Failed to Place Order\nPlease Try Again",
            DeliveryMethodUpdateFailed      : "Failed to Update Delivery Method",
            DeliveryMethodEmptyMessage      : "Please select your delivery address first",
            DeliveryMethodPickupErrorMessage: "No delivery charge applies for self pickup method",
            BillingAddress                  : "Billing Address",
            DeliveryAddress                 : "Delivery Address",
            OrderNote                       : "Order Note",
            PleaseWriteNotesOfYourOrder     : "Please write notes of your order",
            OrderSummary                    : "Order Summary",
            OrderedItems                    : "Ordered Items",
            OrderID                         : "Order ID",
            OrderTime                       : "Order Time",
            PaymentTime                     : "Payment Time",
            ShipTime                        : "Ship Time",
            CompletedTime                   : "Completed Time",
            PickupAddress                   : "Pickup Address",
            Delivery                        : "Delivery",
            AddProductToCart                : "Add a product to the shopping cart",
            TotalPrice                      : "Total Price",
            Qty                             : "Qty",
            YourDeliveryInfo                : "Your delivery info:",
            ShopNow                         : "Shop Now",
            YourChoice                      : "Your wishlist:",
            YourSale                        : "Your Sale:",
            SubtotalPrice                   : "Subtotal Price:",
            BuyNow                          : "Buy Now",
            Items                           : "Items",
            Item                            : "Item",
            ThankYou                        : "Thank you",
            FinishOrderCOD                  : "You can use to number of order to track shipping status",
            FinishOrder                     :
                "Thank you so much for your purchased, to check your delivery status please go to My Orders",
            NextStep                        : "Next Step",
            ConfirmOrder                    : "Confirm Order",
            RequireEnterAllFileds           : "Please enter all fields",
            GoToShop                        : "Go to shop",
            Finish                          : "Finish",
            EMI                             : "EMI",
            for                             : "for",
            PaymentReferenceId              : "Payment Reference Id",
            PaymenFailedDesc                : "Payment processing failed\nPlease try again",

            PleaseSelect: "Please Select",

            // Wishlist
            NoWishListItem           : "There is no item in wishlist",
            MoveAllToCart            : "Add all to cart",
            EmptyWishList            : "Empty wishlist",
            EmptyAddToCart           : "Sorry, the wishlist is empty",
            RemoveWishListItemConfirm: "Remove this product from wishlist?",
            CleanAll                 : "Clean All",

            // Sidemenu
            SignIn                   : "Sign In",
            SignUp                   : "Sign Up",
            SignOut                  : "Sign Out",
            ResetNow                 : "Reset now",
            ResendNow                : "Resend now",
            ResendCode               : "Resend code",
            GuestAccount             : "Guest account",
            CantReactEmailError      :
                "We can't reach your email address, please try other login method",
            NoEmailError             : "Your account don't have valid email address",
            EmailIsNotVerifiedError  :
                "Your email address is not verified, we can' trust you",
            Shop                     : "Shop",
            News                     : "News",
            Contact                  : "Contact us",
            Setting                  : "Setting",
            Login                    : "Login",
            Register                 : "Register",
            LoginRegister            : "Login / Register",
            Registration             : "Registration",
            RegistrationCompleted    : "Registration Completed",
            OrderCompleted           : "Order Completed",
            OrderCompletedDescription: "Your order is placed successfully and already submitted to our warehouse team for dispatch",
            OrderCompletedBackDesc   : "Go back to home page now for more shopping",
            ForgotPassword           : "Forgot Password",
            ResetPassword            : "Reset Password",
            Logout                   : "Logout",
            Submit                   : "Submit",
            Success                  : "Success",
            Male                     : "Male",
            Female                   : "Female",
            Other                    : "Other",
            Category                 : "Category",
            Registering              : "Registering",
            Change                   : "Change",
            ChangePassword           : "Change password",
            UpdateProfile            : "Update profile",
            ChangePhoto              : "Change Photo",
            PlaceOrder               : "Place Order",
            OpeningHours             : "Opening Hours",
            PickupFee                : "Pickup Fee",

            // Checkout
            Checkout                   : "Checkout",
            ProceedPayment             : "Proceed Payment",
            Purchase                   : "Purchase",
            CashOnDelivery             : "Cash on Delivery",
            Paypal                     : "Paypal",
            Stripe                     : "Stripe",
            CreditCard                 : "Credit Card",
            PaymentMethod              : "Payment Method",
            PaymentMethodError         : "Please select your payment method",
            PayWithCoD                 : "Your purchase will be pay when goods were delivered",
            PayWithPayPal              : "Your purchase will be pay with PayPal",
            PayWithStripe              : "Your purchase will be pay with Stripe",
            CouponPlaceholder          : "COUPON CODE",
            Apply                      : "Apply",
            Remove                     : "Remove",
            CardNamePlaceholder        : "Name written on card",
            BackToHome                 : "Back to Home",
            OrderWasCompleted          : "Your order was completed",
            OrderCanceled              : "Your order was canceled",
            OrderFailed                : "Something went wrong...",
            OrderCompletedDesc         : "Your order id is ",
            OrderCanceledDesc          :
                "You have canceled the order. The transaction has not been completed",
            OrderFailedDesc            :
                "We have encountered an error while processing your order. The transaction has not been completed. Please try again",
            OrderTip                   :
                'Tip: You could track your order status in "My Orders" section from side menu',
            Payment                    : "Payment",
            Complete                   : "Complete",
            EnterYourFirstName         : "Enter your first name",
            EnterYourLastName          : "Enter your last name",
            EnterYourEmail             : "Enter your email",
            EnterYourPhone             : "Enter your phone",
            EnterYourAddress           : "Enter your address",
            EnterYourPassword          : "Enter your password",
            EnterYourCurrentPassword   : "Enter your current password",
            EnterYourNewPassword       : "Enter your new password",
            ConfirmYourNewPassword     : "Confirm your new password",
            EnterYourConfirmPassword   : "Confirm your password",
            EnterYourNewConfirmPassword: "Confirm your new password",
            EnterResetCode             : "Enter reset code",
            SelectYourDateOfBirth      : "Select your date of birth",
            SelectYourGender           : "Select your gender",
            CreateOrderError           : "Cannot create new order. Please try again later",
            AccountNumner              : "Account number",
            CardHolderName             : "Cardholder Name",
            ExpirationDate             : "Expiration Date",
            SecurityCode               : "CVV",
            EditProfile                : "Edit Profile",

            // myorder
            OrderId     : "Order ID",
            MyOrder     : "My Orders",
            NoOrder     : "You don't have any orders",
            OrderDate   : "Order Date: ",
            OrderStatus : "Status: ",
            OrderPayment: "Payment method: ",
            Refund      : "Refund",

            // settings
            BASICSETTINGS: "BASIC SETTINGS",
            Language     : "Language",
            INFO         : "INFO",
            Information  : "Information",
            changeRTL    : "Switch RTL",

            // language
            AvailableLanguages   : "Available Languages",
            SwitchLanguage       : "Switch Language",
            SwitchLanguageConfirm: "Switch language require an app reload, continue?",
            SwitchRtlConfirm     : "Switch RTL require an app reload, continue?",

            // about us
            AppDescription: "",
            AppContact    : " Contact us at: ",
            AppEmail      : " Email: ",
            AppCopyRights : "© 2020",

            // contact us
            contactus: "Contact us",

            // form
            NotSelected           : "Not selected",
            EmptyError            : "This field is empty",
            DeliveryInfo          : "Delivery Info",
            FirstName             : "First Name",
            LastName              : "Last Name",
            Address               : "Address",
            StreetAddress         : "Street Address",
            City                  : "Town/City",
            PostalCode            : "Postal Code",
            State                 : "State",
            StateDescription      : "Select State",
            CityDescription       : "Select City",
            CountryDescription    : "Select Country",
            NotSelectedError      : "Please choose one",
            Postcode              : "Postcode",
            Country               : "Country",
            Email                 : "Email",
            Phone                 : "Phone",
            PhoneNumber           : "Phone Number",
            DateOfBirth           : "Date of Birth",
            Gender                : "Gender",
            Code                  : "Code",
            Note                  : "Note",
            ReferenceCode         : "Reference Code",
            ReferenceCodeNotUsed  : "Reference Code Not Used",
            Optional              : "Optional",
            AddressNoteDescription: "e.g. Meet me at the lobby",
            SetAsDefaultAddress   : "Set As Default Address",

            // search
            Search             : "Search",
            SearchPlaceHolder  : "Type your keyword",
            SearchProductByName: "Search product by name",
            SearchOf           : "Search of",
            SearchReturned     : "Search returned",
            returned           : "returned",
            Results            : "results",
            NoResultError      : "Your search keyword did not match any products.",
            Details            : "Details",

            // filter panel
            Categories: "Categories",

            // sign up
            profileDetail     : "Profile details",
            firstName         : "First name",
            lastName          : "Last name",
            accountDetails    : "Account details",
            FullName          : "Full Name",
            Username          : "Username",
            email             : "Email",
            generatePass      : "Use generate password",
            Password          : "Password",
            ConfirmPassword   : "Confirm password",
            CurrentPassword   : "Current password",
            NewPassword       : "New password",
            ConfirmNewPassword: "Confirm new password",
            signup            : "Sign up",

            // filter panel
            welcomeBack: "Welcome back ",
            seeAll     : "Show All",

            ID                     : "Id",
            SearchQueryText        : "Search Query Text",
            AddressTitle           : "Address Title",
            AddressTitleDescription: "Name your address to find it easily",
            Coupon                 : "Coupon",
            CouponCode             : "Coupon Code",
            YouHaveGotCoupon       : "You have got coupon",
            ApplyCoupon            : "Apply Coupon",
            couponCodeIsExpired    : "This coupon code is expired",
            invalidCouponCode      : "This coupon code is invalid",
            remove                 : "Remove",
            reload                 : "Reload",
            applyCouponSuccess     : "Congratulations Coupon code applied successfully ",

            CouponApplied   : "Coupon applied\nRM",
            CouponNotWorking: "Coupon not working",
            NoMoreInStock   : "No more in stock",
            ShippingType    : "Shipping type",
            ShippingMethod  : "Shipping method",
            ShippingAddress : "Shipping address",

            // Place holder
            TypeFirstName       : "Type your first name",
            TypeLastName        : "Type your last name",
            TypeAddress         : "Type address",
            TypeCity            : "Type your town or city",
            TypeState           : "Type your state",
            TypeNotSelectedError: "Please choose one",
            TypePostcode        : "Type postcode",
            TypeEmail           : "Type email (Ex. acb@gmail.com), ",
            TypePhone           : "Type your phone number",
            TypeNote            : "Note",
            TypeCountry         : "Select Country",
            SelectPayment       : "Select Payment method",
            Close               : "CLOSE",
            noConnection        : "NO INTERNET ACCESS",

            // user profile screen
            AccountInformations           : "Account Informations",
            PushNotification              : "Push notification",
            DarkTheme                     : "Dark Theme",
            Privacy                       : "Privacy policies",
            SelectDeliveryAddress         : "Select Delivery Address",
            SelectBillingAddress          : "Select Billing Address",
            SelectShippingMethod          : "Select Shipping Method",
            SelectDeliveryMethod          : "Select Delivery Method",
            MembershipType                : "Membership Type",
            InstallmentPeriod             : "Installment Period",
            InstallmentAmount             : "Installment Amount",
            ReadAndAcceptTermsAndCondition: "Please read and accept terms and condtion",
            IAgreeToTermsAndCondition     : "I agree to terms and condition",
            ReadHere                      : "Read here",
            SelectMembershipType          : "Select Membership Type",
            SelectMembershipTypeDesc      : "Choose your desired membership type from the list",
            SelectInstallmentPeriod       : "Select Installment Period",
            SelectInstallmentPeriodDesc   : "Choose your desired instalment period from the list",
            SelectPaymentMethod           : "Select Payment Method",
            SelectAddress                 : "Select Address",
            SelectDeliveryAddressDesc     : "Select delivery address from your saved list",
            SelectBillingAddressDesc      : "Select billing address from your saved list",
            SelectPaymentMethodDesc       : "Choose your desired payment method from the list",
            SelectedPaymentMethodDesc     : "To change your payment method, please tap here",
            SelectedDeliveryMethodDesc    : "To change your delivery method, please tap here",
            SelectedShippingMethodDesc    : "To change your shipping method, please tap here",
            SelectPickupAddress           : "Select Pickup Address",
            SelectPickupAddressDesc       : "Select your preferred pickup address from the list",
            SelectFileSource              : "Select File Source",
            ReceiverDetails               : "Receiver Details",
            ReceiverDetailsDesc           : "Enter the details of receiver who will pickup your order",
            SelectGender                  : "Select Gender",
            ReceiverName                  : "Receiver's Name",
            ReceiverPhoneNumber           : "Receiver's Phone Number",
            ReceiverICPassport            : "Receiver's IC/Passport",
            SelectCountry                 : "Select Country",
            SelectState                   : "Select State",
            SelectCity                    : "Select City",
            SelectCurrency                : "Select Currency",
            SelectLocation                : "Select Location",
            CancelOrder                   : "Cancel Order",
            CancelOrderDesc               : "If you want to cancel this order, please tap here",
            ReturnOrder                   : "Return Order",
            ReturnOrderDesc               : "If you want to return this order, please tap here",
            UploadReceipt                 : "Upload Receipt",
            UploadReceiptDesc             : "To upload your payment receipt, please tap here",
            SelectLocationDesc            : "Use for higher location accuracy and easier address input",
            DeleteAddress                 : "Delete Address",
            DeleteAddressDesc             : "Use for higher location accuracy and easier address input",
            AddANewAddress                : "Add a new address",
            SelfPickup                    : "Self Pickup",
            CourierService                : "Courier Service",
            Name                          : "Name",
            Currency                      : "Currency",
            Languages                     : "Languages",
            Camera                        : "Camera",
            CameraSelectionDescription    : "Open your camera to take photo",
            Gallery                       : "Gallery",
            GallerySelectionDescription   : "To pick photo from your gallery",
            OtherFiles                    : "Other Files",
            OtherFilesSelectionDescription: "To select any other file type such as pdf/doc/txt/...",

            GetDataError   : "Can't get data from server",
            UserOrEmail    : "Username or email",
            Or             : "Or",
            FacebookLogin  : "Facebook Login",
            DontHaveAccount: "Don't have an account?",

            // Modal
            Sold     : "Sold",
            Available: "Available",
            Select   : "Select",
            Cancel   : "Cancel",
            LoginNow : "Login Now",
            UpdateNow: "Update Now",
            Guest    : "Guest",

            LanguageName: "English",

            // review
            vendorTitle     : "Vendor",
            comment         : "Leave a review",
            yourcomment     : "Your comment",
            placeComment    :
                "Tell something about your experience or leave a tip for others",
            writeReview     : "Review",
            thanksForReview :
                "Thanks for the review, your content will be verify by the admin and will be published later",
            errInputComment : "Please input your content to submit",
            errRatingComment: "Please rating to submit",
            send            : "Send",

            Shipping      : "Shipping",
            TermsCondition: "Terms & Condition",
            PriceBreakdown: "Price Breakdown",
            CartItems     : "Cart Items",

            Subtotal      : "Subtotal",
            Discount      : "Discount",
            Discounted    : "Discounted",
            Voucher       : "Voucher",
            DeliveryCharge: "Delivery Charge",
            ServiceCharge : "Service Charge",
            Tax           : "Tax",
            Total         : "Total",


            Recents       : "Recents",
            Filters       : "Filters",
            Princing      : "Pricing",
            Filter        : "Filter",
            ClearFilter   : "Clear Filter",
            ProductCatalog: "Product Catalog",
            ProductTags   : "Product Tags",
            AddToAddress  : "Add to Address",
            SMSLogin      : "SMS Login",
            OrderNotes    : 'Order Notes'
        },
        bn: {},
    }
);
